export enum OrganizationTypes {
    HOSPITAL = 'HOSPITAL',
    CLINIC = 'CLINIC',
    LABORATORY = 'LABORATORY',
    PHARMACY = 'PHARMACY',
    REHABILITATION_CENTER = 'REHABILITATION_CENTER',
    NURSING_HOME = 'NURSING_HOME',
    MEDICAL_RESEARCH_INSTITUTE = 'MEDICAL_RESEARCH_INSTITUTE',
    AMBULATORY_CARE_CENTER = 'AMBULATORY_CARE_CENTER',
    DIAGNOSTIC_IMAGING_CENTER = 'DIAGNOSTIC_IMAGING_CENTER',
    MENTAL_HEALTH_FACILITY = 'MENTAL_HEALTH_FACILITY'
}